ad2dispatch/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout, password_change
from axes.decorators import watch_login

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/profile/', include('userprofiles.urls', namespace="userprofiles")),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^volunteer/', include('events.urls', namespace="events")),
    # url(r'^dispatch/', include('dispatch.urls', namespace="dispatch")),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^', include('pages.urls', namespace="pages")),
]

news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<article_id>[0-9]+)/$', views.article, name='article'),
]

events/models.py
from __future__ import print_function
from __future__ import unicode_literals

from datetime import timedelta

from django.template import defaultfilters
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=32, null=False)
    date_time = models.DateTimeField(null=False)
    duration = models.DurationField(null=False, help_text='Format as hh:mm:ss')  # Max of 9 days per bigint storage
    location = models.CharField(max_length=64, null=True, blank=True)
    attire = models.CharField(max_length=64, null=True, blank=True)
    details = models.TextField(null=True, blank=True)
    list_date = models.DateField(null=True, blank=True,
                                 help_text='Date that the event should be added to the availability listing. '
                                           'Leaving this blank will add it 30 days prior to the start.')

    def __str__(self):
        return self.title + ' - ' + defaultfilters.date(timezone.localtime(self.date_time), "(D) d M: Hi")

    def summary(self):
        return self

    def end_date_time(self):
        return self.date_time + self.duration

    def days_until(self):
        return timezone.localtime(self.date_time).day - timezone.now().day

    def days_until_msg(self):
        if self.days_until() == 0:
            return 'Today!'
        else:
            return str(self.days_until()) + ' days away'

    def volunteers_type(self, voltype):
        return EventVolunteer.objects.filter(event=self, type=voltype)

    def num_volunteers_type(self, voltype):
        return EventVolunteer.objects.filter(event=self, type=voltype).count()

    def is_during_event(self):
        return timezone.now() > self.date_time and timezone.now < (self.date_time + self.duration)


def position_is_full(event, type):
    max_vols = VolunteerType.objects.get(pk=type).max_volunteers
    if max_vols is None:
        return False
    return EventVolunteer.objects.filter(
        event=Event.objects.get(pk=event),
        type=VolunteerType.objects.get(pk=type)).count() >= max_vols


def get_running_events():
    return Event.objects.filter(date_time__lt=timezone.now(),
                                date_time__gt=(timezone.now() + timedelta(days=-1)))  # TODO Not timedelta


class VolunteerType(models.Model):
    type = models.CharField(max_length=16, null=False)
    max_volunteers = models.IntegerField(null=True, blank=True)
    instructions = models.TextField(null=False)

    def __str__(self):
        return self.type


def get_volunteers(event):
    volunteers = EventVolunteer.objects.filter(event=event).order_by('type')
    for volunteer in volunteers:
        volunteer.profile = volunteer.get_profile()
    return volunteers


class EventVolunteer(models.Model):
    volunteer = models.ForeignKey(User, null=False)
    event = models.ForeignKey(Event, null=False)
    type = models.ForeignKey(VolunteerType, null=False)

    def has_volunteered(self):
        if EventVolunteer.objects.filter(volunteer=self.volunteer, event=self.event, type=self.type).count() > 0:
            return True
        return False

    def get_profile(self):
        from userprofiles.models import Volunteer
        return Volunteer.objects.get(user=self.volunteer)


def do_unvolunteer(vol_event):
    sel = EventVolunteer.objects.get(volunteer=vol_event.volunteer, event=vol_event.event, type=vol_event.type)
    sel.delete()


def has_upcoming_vol(user, type):
    if EventVolunteer.objects.filter(
            volunteer=user,
            type=VolunteerType.objects.get(type=type),
            event__in=Event.objects.filter(date_time__lt=timezone.now() + timedelta(days=30))).count() > 0:
        return True

templates/base.html
<!DOCTYPE html>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>{{ TITLE }}</title>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
<div class="container">
  <!-- MOBILE -->
  <div class="visible-xs-block visible-sm-block mobile">
    <section>
      <!-- Temporary; will be changed to GPS/ID redirect. -->
      <a href="tel:{{ ORG_PHONE }}"><button type="button" class="btn btn-primary btn-block" style="height:3em;font-size:2em;">Call {{ ORG_ACRONYM }}</button></a>
    </section>
    <section>
      <p style="font-size:1.8em;">OR DIAL: {{ ORG_PHONE_DISPLAY }}</p>
    </section>
    <section>
      <p class="disclaimer" style="font-size: 0.8em;">{{ DISCLAIMER }}</p>
    </section>
    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills">
          {% include "navbar.html" %}
        </ul>
      </nav>
    </div>
  </div>
  <!-- END MOBILE -->
  <!-- DESKTOP HEADER -->
  <div class="visible-md-block visible-lg-block">
    <div class="header clearfix">
      <div class="col-md-8" style="margin-bottom:1em;">
        <h1 class="text-muted">{{ ORG_NAME }}</h1>
        <p class="text-muted" style="font-size:0.75em">{{ DISCLAIMER }}</p>
      </div>
      <div class="col-md-4">
        <h2 class="text-muted" style="text-align:right">{{ ORG_PHONE_DISPLAY }}</h2>
      </div>
      <div class="col-md-12">
        <nav>
          <ul class="nav nav-pills pull-right">
            {% include "navbar.html" %}
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <!-- END DESKTOP HEADER -->

{% block content %}
{% endblock %}

</div>
<footer class="footer">
  <div class="container">
    <p class="pull-left">
      {% if FACEBOOK %}
      <a href="https://facebook.com/{{ FACEBOOK }}">
        <img src="{% static 'img/facebook-logo.png' %}" alt="{{ FACEBOOK }} On Facebook" height="35px" width="35px"/>
      </a>
      {% endif %}
      {% if TWITTER %}
      <a href="https://twitter.com/{{ TWITTER }}">
        <img src="{% static 'img/twitter-logo.png' %}" alt="{{ TWITTER }} on Twitter" height="35px" width="35px"/>
      </a>
      {% endif %}
    </p>
    <p class="text-muted pull-right">
      Powered By <a href="https://bitbucket.org/unofficialusafresourcedev/ad2dispatch">ad2dispatch</a>
    </p>
  </div>
</footer>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

templates/events_subnav.html
{% if user.is_authenticated %}
<div class="header clearfix">
	<div class="col-md-12 sub-nav">
		<nav>
			<ul class="nav nav-pills pull-right">
				{% if volunteer.is_driver %}
					<li role="presentation" class="{% if request.path == '/volunteer/driver/' %}active{% endif %}"><a href="/volunteer/driver/">Driver Info</a></li>
				{% endif %}
				{% if volunteer.is_dispatcher %}
                    <li role="presentation" class="{% if request.path == '/volunteer/dispatcher/' %}active{% endif %}"><a href="/volunteer/dispatcher/">Dispatcher Info</a></li>
				{% endif %}
				{% if perms.events.change_eventvolunteer %}
					<li role="presentation" class="{% if request.path == '/volunteer/manage/' %}active{% endif %}"><a href="/volunteer/manage/">Manage</a></li>
				{% endif %}
			</ul>
		</nav>
	</div>
</div>
{% endif %}

templates/flash.html
{% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
{% if flash_type == 'success' %}
    <div class="alert alert-success" role="alert">{{ flash_message|safe }}</div>
{% endif %}
{% if flash_type == 'info' %}
    <div class="alert alert-info" role="alert">{{ flash_message|safe }}</div>
{% endif %}
{% if flash_type == 'warning' %}
    <div class="alert alert-warning" role="alert">{{ flash_message|safe }}</div>
{% endif %}
{% if flash_type == 'danger' %}
    <div class="alert alert-danger" role="alert">{{ flash_message|safe }}</div>
{% endif %}

templates/navbar.html
{% if top_pages %}
    {% for tpage in top_pages %}
        <li role="presentation" class="{% if tpage.loc in loc %}active{% endif %}"><a href="{{ tpage.path }}">{{ tpage.title }}</a></li>
    {% endfor %}
{% endif %}
<li role="presentation" class="{% if '/news/' in request.path %}active{% endif %}"><a href="{% url 'news:index' %}">News</a></li>
<li role="presentation" class="{% if '/volunteer/' in request.path %}active{% endif %}"><a href="/volunteer/">Volunteer</a></li>
{% if user.is_staff %}
    <li role="presentation"><a href="/admin">Admin</a></li>
{% endif %}
{% if user.is_authenticated %}
    <li role="presentation" class="{% if request.path == '/accounts/profile/' %}active{% endif %}"><a href="/accounts/profile/">Profile</a></li>
    <li role="presentation"><a href="/accounts/logout/">Logout</a></li>
{% else %}
    <li role="presentation" class="{% if request.path == '/accounts/login/' %}active{% endif %}"><a href="/accounts/login/">Login</a></li>
    <li rold="presentation" class="{% if request.path == '/accounts/register/' %}active{% endif %}"><a href="/accounts/register/">Register</a></li>
{% endif %}